### ISSUE TITLE
website takes over 20 minutes to build

### ISSUE THREAD

**Issue by brunoamaral** [brunoamaral/gregory-ms-website#2]
```
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

                   |  EN    
-------------------+--------
  Pages            | 15656  
  Paginator pages  |  3635  
  Non-page files   |   123  
  Static files     |  1749  
  Processed images |    93  
  Aliases          | 14612  
  Sitemaps         |     1  
  Cleaned          |     0  

Total in 1429183 ms
```

Either stop using Hugo or use JS to fetch the articles from the database. Suggestions are welcome.

**Comment by brunoamaral** [comment]
During this time, the API does not respond. Alternative is to use something like Elm to fetch data instead of continuously building 15k pages.

**Comment by dippas** [comment]
we can use asynchronous calls in JS either using fetch or promises

**Comment by brunoamaral** [comment]
that's the route I was planning, just not sure if I should take the opportunity to move from Hugo to something like Vue / Elm / React.

Depends on what is easier.

**Comment by dippas** [comment]
I can help With React, I'm working currently with React+TS

**Comment by brunoamaral** [comment]
Thinking about rewriting the article list and single article views with HTMX. Because it seems to be easy enough to maintain alongside Hugo and simple enough that I can understand it 🙂

**Comment by brunoamaral** [comment]
I couldn't use htmx properly, so now I am trying with react: https://github.com/brunoamaral/gregory-ms-website/tree/react

**Comment by brunoamaral** [comment]
Articles are now rendered from the API 😁 https://github.com/brunoamaral/gregory-ms-website/pull/12 closes this issue.
